### ISSUE TITLE
Merge BraveChatbot repo into BraveButtons

### ISSUE THREAD

**Issue by mariocimet** [bravetechnologycoop/BraveButtons#10]

**Comment by mariocimet** [comment]
@schwarrrtz note that we'll have to fix the link for the Travis button in Readme when this is done

**Comment by schwarrrtz** [comment]
ok so i've merged the chatbot code into this repo (in 5f3ee3c0b4810e0a246) and also redid the tags in this repo to point to the various chatbot and pi/heartbeat versions prior to the merge.

**Comment by schwarrrtz** [comment]
@trisapeace do we need to change any of the travis config at this point?

**Comment by trisapeace** [comment]
@schwarrrtz Yup, good point.
I just started working on it in this branch: fix-checkout-travis

I've gotten it to the point where it's complaining that it can't find mocha. So I'll need to look into that more. 

We're also going to get to the point where it'll need the TWILIO_SID_TEST and TWILIO_TOKEN_TEST environment variables set up in Travis. I don't have those at home, but I think that either you or @mariocimet would be able to add them by signing in to Travis with your GitHub account, clicking on any of the BraveButton runs, then clicking on More Options --> Settings. From there you can add the two environment variables. Please make sure that you leave the "Display value in build log" toggle turned off. That will keep the value secret.

**Comment by schwarrrtz** [comment]
@trisapeace just added those two environment variables.

Let's close this issue once Travis is working with the new repo structure? To me it feels like part of the process of merging the two repos.

**Comment by trisapeace** [comment]
@schwarrrtz This issue's good to close now that you've merged #17 , right?

**Comment by schwarrrtz** [comment]
yes i think so!
