### ISSUE TITLE
Automatic log rotation

### ISSUE THREAD

**Issue by mariocimet** [bravetechnologycoop/BraveButtons#12]
Log files keep growing to an unmanageable size, we want to prevent this.

**Comment by mariocimet** [comment]
See pull-request #15. This looks like it has a good chance of addressing this for the server. We're unsure what would happen if we just installed and configured pm2-logrotate on the production server, we can try this out on heartbeat-dev first. 

This is also a worry for the pi's, where the log files also get huge, [this python class](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) looks roughly equivalent to pm2-logrotate for servers - it lets you specify max bytes and number of files to retain.

**Comment by mariocimet** [comment]
hey @schwarrrtz just checking where we're at with this - are you completing this for the pi?

**Comment by schwarrrtz** [comment]
yep! see pr #16

**Comment by schwarrrtz** [comment]
ok so i've merged #15 and #16 after a week of testing, but we still need to add log rotation for the chatbot server

**Comment by schwarrrtz** [comment]
ok chatbot server log rotation is added in #18. will close this once that is tested and merged.

**Comment by mariocimet** [comment]
sweet!
