### ISSUE TITLE
Create scheduled system maintenance process user checklist

### ISSUE THREAD

**Issue by mariocimet** [bravetechnologycoop/BraveButtons#14]
Where we check for:
Certificate validity
Deploy updates
Check Microsoft Flow

**Comment by schwarrrtz** [comment]
i don't think we need to check for certificate validity since it should get handled automatically by the certbot cron we use. and i don't think deploying updates per se should be something that we do on a fixed schedule - it should happen when we have an update ready to deploy.

**Comment by schwarrrtz** [comment]
i do agree that we could check the microsoft flow status on a fairly regular basis. and there a few other things we could check / do on a regular basis as well:

- check logs for unusual behaviour (chatbot logs, twilio logs, heartbeat logs, syslogs...)
- rotate passwords
- check for available updates on our dependencies, but don't apply them until we test them (this might include updates to npm modules, python modules, raspbian, ubuntu, etc)

**Comment by mariocimet** [comment]
Let's give this a shot next Wednesday with @trisapeace

**Comment by schwarrrtz** [comment]
just for future reference, Mario made a recurring calendar event for us to go over the maintenance checklist. right now the checklist only exists as the agenda for this event, but maybe in the future we could make a google doc or something.
