### ISSUE TITLE
Potential filename collision.

### ISSUE THREAD

**Issue by darvell** [bravetechnologycoop/BraveButtons#64]
https://github.com/bravetechnologycoop/BraveButtons/blob/3552927c3ff88684ee58dcd5ead2f355a324b98b/pairing-tool/index.js#L10

Using random numbers can cause collisions inadvertently which would lead to data loss. Also you lose context. Here are some suggestions.

If random, use a UUID.
```
import { v4 as uuidv4 } from 'uuid';
const outputFile = `./pairing-tool-output-${uuidv4().replace("-","")}.csv
```

Use the unix timestamp to identify when the pairing tool was ran in the filename.
```
const outputFile = `./pairing-tool-output-${Date.now() / 1000 | 0}.csv
```

If nanosecond timing is wanted with the timestamp idea, node provides this.
```
const hrTime = process.hrtime();
const curMicroseconds = hrTime[0] * 1000000000 + hrTime[1];
const outputFile = `./pairing-tool-output-${curMicroseconds}.csv
```

**Comment by darvell** [comment]
Though I need to read through it all, should this not all just work with a local sqlite database to record all attempts with timestamps and potential revocations? There's still other automations to look in to though so that could be for another issue or PR.

**Comment by trisapeace** [comment]
Hi Darvell,

Thanks for thinking of this. We actually don't end up keeping the auto-generated filename for very long. We almost immediately rename it to YYYY-MM-DD-<client>-<some other description>.csv before moving it to the `buttons-config` repo. So I don't think it's a concern that we might overwrite an older local version of the file.

@schwarrrtz , have I got that right?
