### ISSUE TITLE
Add a test harness for the twilio functions

### ISSUE THREAD

**Issue by mariocimet** [bravetechnologycoop/BraveButtons#8]
We aren't testing the fallback phone number functionality with the current test harness, and doing so requires having more than the single test phone number that twilio provides us. The goal for this issue is to set up a small mocked version of the twilio API to be able to test this.

**Comment by mariocimet** [comment]
Documenting a first try at this:

we're defining server.faketwilio, and assigning it a value within each test we want to use it in. Based on whether or not we're in the 'test' environment we use real or fake twilio.

**Comment by mariocimet** [comment]
Right now the tests all pass whether or not twilioClient is actually defined. None of our tests depend on what the twilioClient returns (or whether it actually sends the message we want it to).

**Comment by mariocimet** [comment]
In server.js, insofar as we care at all about what the twilio client returns its only to log it.

**Comment by mariocimet** [comment]
What do we actually want to do with the responses from Twilio? If the API request fails?

@trisapeace says retry at least once, and possibly message somebody (Slack?) at Brave if that happens.

**Comment by mariocimet** [comment]
Mocking right now is probably not the priority - I'll go ahead and try to write a test for the fallback phone which may or may not involve mocking.

**Comment by schwarrrtz** [comment]
ok so @mariocimet wrote a test for the fallback alert that did not involve mocking. i'd say that's a good first step towards testing the twilio functionality. we can reassess whether we want to build out a test harness for the rest of the twilio code as a separate issue.
